#!/usr/bin/env python3
"""
seed_test_data.py
Seeds IAM system with test data for performance testing.

Supports multiple IAM backends via IAM_PROVIDER environment variable:
  - ferriskey (default)
  - keycloak

Usage:
    # FerrisKey (default)
    python scripts/seed_test_data.py

    # Keycloak
    IAM_PROVIDER=keycloak python scripts/seed_test_data.py

Configuration is read from .env file or environment variables.
After seeding, a .env.test file is generated with all k6 test configuration.
"""

import sys
from pathlib import Path

from lib import (
    load_config,
    print_error,
    print_success,
    print_warning,
    FerrisKeyProvider,
    KeycloakProvider,
    IAMProvider,
)


def get_provider(provider_name: str, config) -> IAMProvider:
    """Get the appropriate IAM provider based on configuration."""
    providers = {
        "ferriskey": FerrisKeyProvider,
        "keycloak": KeycloakProvider,
    }

    provider_class = providers.get(provider_name.lower())
    if not provider_class:
        print_error(f"Unknown IAM provider: {provider_name}")
        print_error(f"Supported providers: {', '.join(providers.keys())}")
        sys.exit(1)

    return provider_class(config)


def write_test_env_file(
    config,
    client_id: str,
    client_secret: str,
    output_path: Path,
) -> None:
    """Write a .env.test file with all k6 test configuration."""
    content = f"""# Generated by seed_test_data.py
# Use this file to run k6 tests:
#   set -a && source .env.test && set +a && k6 run k6/scenarios/token_client_credentials.js

# Server connection
BASE_URL={config.base_url}

# Test realm
REALM={config.perf_realm}

# Client credentials
CLIENT_ID={client_id}
CLIENT_SECRET={client_secret}

# Test user credentials
TEST_USERNAME={config.user_prefix}001
TEST_PASSWORD={config.user_password}

# k6 test parameters (adjust as needed)
VUS=50
DURATION=5m
"""
    output_path.write_text(content)
    print_success(f"Test configuration written to: {output_path}")


def main() -> None:
    # Load configuration
    config = load_config()

    # Get the appropriate provider
    provider = get_provider(config.iam_provider, config)

    print_success(f"=== {provider.name} Performance Test Data Seeding ===")
    print(f"Provider: {provider.name}")
    print(f"Base URL: {config.base_url}")
    print(f"Admin Realm: {config.admin_realm}")
    print(f"Perf Realm: {config.perf_realm}")
    print(f"Client ID: {config.client_id}")
    print(f"User Count: {config.user_count}")
    print()

    # Step 1: Get admin token
    print_warning("Step 1: Authenticating as admin...")
    admin_token = provider.get_admin_token()
    print()

    # Step 2: Create performance test realm
    print_warning("Step 2: Creating performance test realm...")
    provider.create_realm(admin_token, config.perf_realm)
    print()

    # Step 3: Create test client from env configuration
    print_warning(f"Step 3: Creating test client '{config.client_id}'...")
    client_uuid, client_secret = provider.create_default_client(admin_token, config.perf_realm)

    if not client_uuid:
        print_error("Failed to create client. Aborting.")
        sys.exit(1)

    if not client_secret:
        print_error("Failed to retrieve client secret. Aborting.")
        sys.exit(1)

    print()

    # Step 4: Create test users
    print_warning(f"Step 4: Creating test users ({config.user_count} users)...")
    created = 0
    failed = 0

    for i in range(1, config.user_count + 1):
        padded = f"{i:03d}"
        username = f"{config.user_prefix}{padded}"
        firstname = config.user_firstname
        lastname = f"{config.user_lastname_prefix}{padded}"
        email = f"{config.user_email_prefix}{padded}@{config.user_email_domain}"

        # Show progress every 10 users
        if i % 10 == 0 or i == config.user_count:
            print(f"  Creating users... {i}/{config.user_count}")

        user_id = provider.create_user(
            admin_token, config.perf_realm, username, firstname, lastname, email
        )

        if user_id:
            # Set password for the user
            if provider.set_user_password(
                admin_token, config.perf_realm, user_id, config.user_password
            ):
                created += 1
            else:
                failed += 1
        else:
            failed += 1

    print_success(f"Users created: {created}, Skipped/Failed: {failed}")
    print()

    # Step 5: Write test configuration file
    print_warning("Step 5: Writing test configuration file...")
    script_dir = Path(__file__).parent
    env_test_path = script_dir.parent / ".env.test"
    write_test_env_file(config, config.client_id, client_secret, env_test_path)
    print()

    # Summary
    print_success("=== Seeding Complete ===")
    print()
    print("Test configuration:")
    print(f"  Provider: {provider.name}")
    print(f"  Realm: {config.perf_realm}")
    print(f"  Client ID: {config.client_id}")
    print(f"  Client Secret: {client_secret}")
    print(f"  Test users: {config.user_prefix}001 through {config.user_prefix}{config.user_count:03d}")
    print(f"  User password: {config.user_password}")
    print()
    print("To run k6 tests:")
    print("  set -a && source .env.test && set +a && k6 run k6/scenarios/token_client_credentials.js")


if __name__ == "__main__":
    main()
